package syntactic.exceptions;

public enum ErrorType {
	INVALID_COORDINATE,
	UNEXPECTED_CHARACTER,
	MISSING_APOSTROPHE,
	INVALID_CHARACTER,
	INVALID_OPERATOR,
	INVALID_TYPE,
	MISSING_NEWLINE,
	MISSING_SPACE,
	PARAMETER_COUNT_MISMATCH,
	RESERVED_KEYWORD,
	REDECLARED_VARIABLE,
	UNDECLARED_VARIABLE,
	UNDECLARED_METHOD,
	UNEXPECTED_TOKEN;
}
